-- MySQL Script generated by MySQL Workbench
-- Tue Jul  8 15:25:08 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bd_trukea
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bd_trukea` ;

-- -----------------------------------------------------
-- Schema bd_trukea
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_trukea` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `bd_trukea` ;

-- -----------------------------------------------------
-- Table `bd_trukea`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_trukea`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `correo` VARCHAR(100) NOT NULL,
  `contraseña` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `correo` (`correo` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bd_trukea`.`calificaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_trukea`.`calificaciones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario_calificador_id` INT NULL DEFAULT NULL,
  `usuario_calificado_id` INT NULL DEFAULT NULL,
  `puntuacion` INT NULL DEFAULT NULL,
  `comentario` TEXT NULL DEFAULT NULL,
  `fecha` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `usuario_calificador_id` (`usuario_calificador_id` ASC) VISIBLE,
  INDEX `usuario_calificado_id` (`usuario_calificado_id` ASC) VISIBLE,
  CONSTRAINT `calificaciones_ibfk_1`
    FOREIGN KEY (`usuario_calificador_id`)
    REFERENCES `bd_trukea`.`usuarios` (`id`),
  CONSTRAINT `calificaciones_ibfk_2`
    FOREIGN KEY (`usuario_calificado_id`)
    REFERENCES `bd_trukea`.`usuarios` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bd_trukea`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_trukea`.`categorias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bd_trukea`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_trukea`.`category` (
  `category_id` INT NOT NULL,
  `category_name` VARCHAR(100) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bd_trukea`.`cities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_trukea`.`cities` (
  `city_id` INT NOT NULL,
  `city_name` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`city_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bd_trukea`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_trukea`.`users` (
  `user_id` INT NOT NULL,
  `first_name` VARCHAR(50) NULL DEFAULT NULL,
  `last_name` VARCHAR(50) NULL DEFAULT NULL,
  `middle_name` VARCHAR(50) NULL DEFAULT NULL,
  `birth_date` DATE NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `city_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE,
  INDEX `city_id` (`city_id` ASC) VISIBLE,
  CONSTRAINT `users_ibfk_1`
    FOREIGN KEY (`city_id`)
    REFERENCES `bd_trukea`.`cities` (`city_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bd_trukea`.`quality`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_trukea`.`quality` (
  `quality_id` INT NOT NULL,
  `quality_name` VARCHAR(50) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`quality_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bd_trukea`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_trukea`.`products` (
  `product_id` INT NOT NULL,
  `product_name` VARCHAR(100) NULL DEFAULT NULL,
  `product_description` TEXT NULL DEFAULT NULL,
  `product_condition` VARCHAR(50) NULL DEFAULT NULL,
  `valor_estimado` INT NULL DEFAULT NULL,
  `quality_id` INT NULL DEFAULT NULL,
  `product_category` INT NULL DEFAULT NULL,
  PRIMARY KEY (`product_id`),
  INDEX `quality_id` (`quality_id` ASC) VISIBLE,
  INDEX `product_category` (`product_category` ASC) VISIBLE,
  CONSTRAINT `products_ibfk_1`
    FOREIGN KEY (`quality_id`)
    REFERENCES `bd_trukea`.`quality` (`quality_id`),
  CONSTRAINT `products_ibfk_2`
    FOREIGN KEY (`product_category`)
    REFERENCES `bd_trukea`.`category` (`category_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bd_trukea`.`listings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_trukea`.`listings` (
  `listing_id` INT NOT NULL,
  `user_id` INT NULL DEFAULT NULL,
  `product_id` INT NULL DEFAULT NULL,
  `publication_date` DATE NULL DEFAULT NULL,
  `closing_date` DATE NULL DEFAULT NULL,
  `city_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`listing_id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  INDEX `product_id` (`product_id` ASC) VISIBLE,
  INDEX `city_id` (`city_id` ASC) VISIBLE,
  CONSTRAINT `listings_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `bd_trukea`.`users` (`user_id`),
  CONSTRAINT `listings_ibfk_2`
    FOREIGN KEY (`product_id`)
    REFERENCES `bd_trukea`.`products` (`product_id`),
  CONSTRAINT `listings_ibfk_3`
    FOREIGN KEY (`city_id`)
    REFERENCES `bd_trukea`.`cities` (`city_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bd_trukea`.`listing_image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_trukea`.`listing_image` (
  `image_id` INT NOT NULL,
  `listing_id` INT NULL DEFAULT NULL,
  `image_url` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`image_id`),
  INDEX `listing_id` (`listing_id` ASC) VISIBLE,
  CONSTRAINT `listing_image_ibfk_1`
    FOREIGN KEY (`listing_id`)
    REFERENCES `bd_trukea`.`listings` (`listing_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bd_trukea`.`listing_status_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_trukea`.`listing_status_history` (
  `history_id` INT NOT NULL,
  `listing_id` INT NULL DEFAULT NULL,
  `status` ENUM('Pendiente', 'Aceptado', 'Cancelado', 'Finalizado') NULL DEFAULT 'Pendiente',
  `changed_at` DATE NULL DEFAULT NULL,
  `changed_by` INT NULL DEFAULT NULL,
  PRIMARY KEY (`history_id`),
  INDEX `listing_id` (`listing_id` ASC) VISIBLE,
  INDEX `changed_by` (`changed_by` ASC) VISIBLE,
  CONSTRAINT `listing_status_history_ibfk_1`
    FOREIGN KEY (`listing_id`)
    REFERENCES `bd_trukea`.`listings` (`listing_id`),
  CONSTRAINT `listing_status_history_ibfk_2`
    FOREIGN KEY (`changed_by`)
    REFERENCES `bd_trukea`.`users` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bd_trukea`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_trukea`.`productos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  `categoria_id` INT NULL DEFAULT NULL,
  `usuario_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `categoria_id` (`categoria_id` ASC) VISIBLE,
  INDEX `usuario_id` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `productos_ibfk_1`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `bd_trukea`.`categorias` (`id`),
  CONSTRAINT `productos_ibfk_2`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `bd_trukea`.`usuarios` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bd_trukea`.`trade_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_trukea`.`trade_history` (
  `trade_id` INT NOT NULL,
  `listing_id` INT NULL DEFAULT NULL,
  `user_1_id` INT NULL DEFAULT NULL,
  `user_2_id` INT NULL DEFAULT NULL,
  `rating_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`trade_id`),
  INDEX `listing_id` (`listing_id` ASC) VISIBLE,
  INDEX `user_1_id` (`user_1_id` ASC) VISIBLE,
  INDEX `user_2_id` (`user_2_id` ASC) VISIBLE,
  INDEX `rating_id` (`rating_id` ASC) VISIBLE,
  CONSTRAINT `trade_history_ibfk_1`
    FOREIGN KEY (`listing_id`)
    REFERENCES `bd_trukea`.`listings` (`listing_id`),
  CONSTRAINT `trade_history_ibfk_2`
    FOREIGN KEY (`user_1_id`)
    REFERENCES `bd_trukea`.`users` (`user_id`),
  CONSTRAINT `trade_history_ibfk_3`
    FOREIGN KEY (`user_2_id`)
    REFERENCES `bd_trukea`.`users` (`user_id`),
  CONSTRAINT `trade_history_ibfk_4`
    FOREIGN KEY (`rating_id`)
    REFERENCES `bd_trukea`.`rating` (`rating_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bd_trukea`.`rating`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_trukea`.`rating` (
  `rating_id` INT NOT NULL,
  `trade_id` INT NULL DEFAULT NULL,
  `rater_user_id` INT NULL DEFAULT NULL,
  `rated_user_id` INT NULL DEFAULT NULL,
  `score` TINYINT NULL DEFAULT NULL,
  `rated_at` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`rating_id`),
  INDEX `fk_rating_trade` (`trade_id` ASC) VISIBLE,
  CONSTRAINT `fk_rating_trade`
    FOREIGN KEY (`trade_id`)
    REFERENCES `bd_trukea`.`trade_history` (`trade_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bd_trukea`.`safe_zone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_trukea`.`safe_zone` (
  `zone_id` INT NOT NULL,
  `zone_name` VARCHAR(100) NULL DEFAULT NULL,
  `address` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`zone_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bd_trukea`.`safe_zone_schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_trukea`.`safe_zone_schedule` (
  `schedule_id` INT NOT NULL,
  `zone_id` INT NULL DEFAULT NULL,
  `day_of_week` ENUM('Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado', 'Domingo') NULL DEFAULT NULL,
  `opening_time` TIME NULL DEFAULT NULL,
  `closing_time` TIME NULL DEFAULT NULL,
  PRIMARY KEY (`schedule_id`),
  INDEX `zone_id` (`zone_id` ASC) VISIBLE,
  CONSTRAINT `safe_zone_schedule_ibfk_1`
    FOREIGN KEY (`zone_id`)
    REFERENCES `bd_trukea`.`safe_zone` (`zone_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bd_trukea`.`trade_request`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_trukea`.`trade_request` (
  `request_id` INT NOT NULL,
  `listing_id` INT NULL DEFAULT NULL,
  `requester_user_id` INT NULL DEFAULT NULL,
  `offered_product_id` INT NULL DEFAULT NULL,
  `status` ENUM('Pendiente', 'Aceptado', 'Rechazado') NULL DEFAULT 'Pendiente',
  `request_date` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`request_id`),
  INDEX `listing_id` (`listing_id` ASC) VISIBLE,
  INDEX `requester_user_id` (`requester_user_id` ASC) VISIBLE,
  INDEX `offered_product_id` (`offered_product_id` ASC) VISIBLE,
  CONSTRAINT `trade_request_ibfk_1`
    FOREIGN KEY (`listing_id`)
    REFERENCES `bd_trukea`.`listings` (`listing_id`),
  CONSTRAINT `trade_request_ibfk_2`
    FOREIGN KEY (`requester_user_id`)
    REFERENCES `bd_trukea`.`users` (`user_id`),
  CONSTRAINT `trade_request_ibfk_3`
    FOREIGN KEY (`offered_product_id`)
    REFERENCES `bd_trukea`.`products` (`product_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bd_trukea`.`trueques`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_trukea`.`trueques` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `producto_ofrecido_id` INT NOT NULL,
  `producto_deseado_id` INT NOT NULL,
  `estado` VARCHAR(50) NULL DEFAULT 'pendiente',
  `fecha` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `producto_ofrecido_id` (`producto_ofrecido_id` ASC) VISIBLE,
  INDEX `producto_deseado_id` (`producto_deseado_id` ASC) VISIBLE,
  CONSTRAINT `trueques_ibfk_1`
    FOREIGN KEY (`producto_ofrecido_id`)
    REFERENCES `bd_trukea`.`productos` (`id`),
  CONSTRAINT `trueques_ibfk_2`
    FOREIGN KEY (`producto_deseado_id`)
    REFERENCES `bd_trukea`.`productos` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
